"""scripts/fresh_start.py — Reset the desk and seed all 10 initial agents.

WARNING: This deletes ALL existing data in the database.
Run only when you want a clean start.
"""
import sys
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from store.db import get_connection, init_schema
from meta.spawner import spawn_agent

DB_PATH = PROJECT_ROOT / "data" / "forge.db"
STARTING_BALANCE = 50_000.0

SEED_AGENTS = [
    (
        "iron_moth",
        "# iron_moth — Thesis v1: Cross-sectional Momentum\n\n"
        "## Edge Hypothesis\n\n"
        "Cross-sectional momentum across the perpetuals universe produces "
        "persistent, uncorrelated alpha that is independent of absolute market "
        "direction. By ranking all assets in the universe on multiple return "
        "horizons (30m, 2h, 12h, 24h) and entering the strongest relative "
        "performers, the agent captures the tendency of winning assets to "
        "continue outperforming losers within the same asset class — the "
        "textbook momentum premium adapted for crypto perps.\n\n"
        "Momentum alone is noisy. The edge is sharpened by requiring "
        "momentum acceleration (the most recent horizon > longer horizons) "
        "and volatility-adjusted returns (Sharpe ratio of the momentum signal "
        "over the lookback). Sector-relative momentum excludes trades that "
        "are just beta — if all assets are rising, the agent prioritises "
        "assets rising the most within their sector peer group. Funding rate "
        "and order book data are explicitly ignored to keep the signal pure.\n\n"
        "## Entry Conditions\n\n"
        "**Required (all must be met):**\n"
        "1. Asset ranks in top 3 of universe by composite momentum score\n"
        "   (weighted average of normalized 30m, 2h, 12h, 24h returns)\n"
        "2. Momentum acceleration confirmed: most recent horizon return\n"
        "   exceeds the average of all longer horizons\n"
        "3. Volatility-adjusted return > 0.5 (return / ATR over lookback)\n"
        "4. Sector-relative rank is top 2 within the asset's sector peer group\n\n"
        "**Supporting (raise confidence, not required):**\n"
        "- Asset is not the highest-correlation member of its sector to BTC\n"
        "- Volume is above the 14-day median (confirms participation)\n"
        "- No conflicting regime tag (e.g. avoid fresh crisis regime)\n\n"
        "## Position Parameters\n\n"
        "- Direction: Long only (cross-sectional momentum on perps favors\n"
        "  the long side due to funding cost on shorts)\n"
        "- Leverage: 3x\n"
        "- Position size: 12% of account per trade\n"
        "- Stop loss: 2.5% below entry price\n"
        "- Take profit: 5.0% above entry price (2:1 reward/risk)\n"
        "- Max hold time: 12 hours; if TP not hit, re-evaluate at next wake\n\n"
        "## Known Weaknesses\n\n"
        "- Underperforms during sharp trend reversals when momentum flips\n"
        "- High correlation to other long-biased strategies on the desk\n"
        "- Mean-reversion regimes (range_high_vol) generate whipsaws\n"
        "- In low-vol regimes the ranking becomes noise-dominated\n\n"
        "## Assets in Focus\n\n"
        "Primary: SOL, ETH, SUI, AVAX, LINK (higher momentum dispersion)\n"
        "Secondary: BTC (lower momentum variance but anchor position)\n"
        "Avoid: Stablecoin pairs and assets with <$50M daily volume\n",
    ),
    (
        "silver_basin",
        "# silver_basin — Thesis v1: Funding Dislocation\n\n"
        "## Edge Hypothesis\n\n"
        "Funding rates are the purest expression of leverage demand in the "
        "crypto perpetuals market. When traders are willing to pay extreme "
        "premiums (positive funding) or receive extreme discounts (negative "
        "funding), they are expressing a conviction that is statistically "
        "likely to be wrong at the extreme. Funding dislocations are "
        "self-correcting: the cost of holding a trade mechanically reduces "
        "the edge of the crowded side until it unwinds.\n\n"
        "This agent studies nothing but funding. It computes the current "
        "funding rate z-score vs a rolling 14-day history, the funding trend "
        "(direction of the last 3 periods), predicted funding from OI changes "
        "(when OI surges, funding tends to follow), and funding acceleration "
        "(the rate of change of funding itself). Entry is triggered when "
        "funding is statistically irrational — extreme z-scores combined with "
        "accelerating trend — and held until funding normalises. Price action "
        "is deliberately excluded to avoid confirmation bias.\n\n"
        "## Entry Conditions\n\n"
        "**Required (all must be met):\n"
        "1. Funding rate z-score > 2.0 (positive extreme) or < -2.0 (negative\n"
        "   extreme) against 14-day rolling window\n"
        "2. Funding acceleration confirms the extreme — the last period's\n"
        "   change is in the same direction as the dislocation\n"
        "3. OI change supports the thesis: for positive funding extreme,\n"
        "   OI should be flat or falling (late-stage crowding); for negative\n"
        "   funding extreme, OI should be stable or rising (building shorts)\n"
        "4. No major scheduled event for the asset in the next 4 hours\n"
        "   (earnings, major unlocks, regulatory decisions)\n\n"
        "**Supporting (raise confidence, not required):**\n"
        "- Funding has been extreme for 2+ consecutive periods (persistence)\n"
        "- Predicted funding from OI model agrees with current extreme\n"
        "- Other assets in same sector show normal funding (idiosyncratic)\n\n"
        "## Position Parameters\n\n"
        "- Direction: For positive extreme: Short (fade the long premium).\n"
        "  For negative extreme: Long (fade the short premium)\n"
        "- Leverage: 4x (higher leverage because mean reversion is time-bound\n"
        "  by funding settlement)\n"
        "- Position size: 10% of account per trade\n"
        "- Stop loss: 2.0% from entry (tight — if funding doesn't revert soon,\n"
        "  the thesis is wrong)\n"
        "- Take profit: Exit when funding z-score returns to within ±1.0\n"
        "  (the signal resolves, not a price target)\n"
        "- Max hold time: Until next funding settlement (max 8 hours)\n\n"
        "## Known Weaknesses\n\n"
        "- In persistent trends, funding can stay extreme for days — this\n"
        "  agent bleeds to the trend\n"
        "- Most correlated to `jade_hawk` (regime detector) — extreme funding\n"
        "  is often a regime signal itself\n"
        "- Low volatility regimes with stable funding produce no signals\n"
        "- Gap risk: funding normalises via a sharp move that hits the SL\n"
        "  first, then continues in the thesis direction\n\n"
        "## Assets in Focus\n\n"
        "Primary: SOL, ETH, ARB, OP, SUI (high funding variance)\n"
        "Secondary: BTC (lower funding variance but deeper liquidity)\n"
        "Avoid: PEPE, DOGE, WIF (funding too noisy, low predictive value)\n",
    ),
    (
        "copper_vane",
        "# copper_vane — Thesis v1: Open Interest Intelligence\n\n"
        "## Edge Hypothesis\n\n"
        "Open interest reveals conviction behind price moves better than "
        "price alone. The OI×Price regime matrix classifies market states "
        "into four categories, each with a clear directional implication:\n\n"
        "- Rising price + rising OI = genuine new participation. Capital is\n"
        "  entering the asset, longs and shorts are both adding. This is\n"
        "  a healthy trend — go with it.\n"
        "- Rising price + falling OI = short squeeze or distribution. Price\n"
        "  is rising but total exposure is shrinking — shorts are being\n"
        "  forced out or smart money is distributing. Fade the move.\n"
        "- Falling price + rising OI = aggressive new shorts. Capital is\n"
        "  entering on the short side, indicating informed selling. Join it.\n"
        "- Falling price + falling OI = longs giving up. Capitulation without\n"
        "  new short conviction — wait for reversal.\n\n"
        "OI data from Hyperliquid updates every few seconds and reflects "
        "real on-chain positioning. This signal is difficult to spoof and "
        "leads price, especially at turning points. The agent ignores raw "
        "price action as a primary signal and classifies every 4-hour window "
        "into one of the four OI×Price quadrants, entering only when the "
        "classification is unambiguous.\n\n"
        "## Entry Conditions\n\n"
        "**Required (all must be met):**\n"
        "1. Clear OI×Price regime classification confirmed for the current\n"
        "   4-hour window with no ambiguity (direction consistency in both\n"
        "   axes over the full window)\n"
        "2. OI change magnitude > 3% in the classification direction\n"
        "   (confirms the signal is meaningful, not noise)\n"
        "3. Price change magnitude > 1.5% (confirms the move has market\n"
        "   impact)\n"
        "4. No conflicting OI regime in the prior 4-hour window\n"
        "   (reversal signals require two consecutive windows to confirm)\n\n"
        "**Supporting (raise confidence, not required):**\n"
        "- Volume confirms: volume direction matches OI direction\n"
        "- Funding rate is neutral or supports the OI thesis\n"
        "- The OI change is broad across the sector (not just one asset)\n\n"
        "## Position Parameters\n\n"
        "- Direction: Determined by OI×Price quadrant classification.\n"
        "   Rising+Rising = Long. Rising+Falling = Short. Falling+Rising =\n"
        "   Short. Falling+Falling = Wait (no entry).\n"
        "- Leverage: 3x\n"
        "- Position size: 12% of account per trade\n"
        "- Stop loss: 2.0% from entry\n"
        "- Take profit: 4.0% from entry (2:1 reward/risk)\n"
        "- Max hold time: 8 hours\n\n"
        "## Known Weaknesses\n\n"
        "- In low-volume regimes, OI changes are small and classification\n"
        "  becomes unreliable\n"
        "- OI data can lag during high-volatility events on Hyperliquid\n"
        "- After large liquidation cascades, OI drops mechanically — this\n"
        "  creates false 'falling+falling' signals\n"
        "- Most effective on mid-cap perps (SOL, ARB, SUI) where OI\n"
        "  changes are driven by conviction, not passive hedging\n\n"
        "## Assets in Focus\n\n"
        "Primary: SOL, ETH, SUI, ARB, OP (good OI depth)\n"
        "Secondary: BTC, BNB (deep OI but lower predictive variance)\n"
        "Avoid: Assets with <$10M OI (noise-dominated)\n",
    ),
    (
        "gray_finch",
        "# gray_finch — Thesis v1: Order Book Microstructure\n\n"
        "## Edge Hypothesis\n\n"
        "Over short time horizons (5-20 minutes), order book microstructure "
        "predicts imminent price direction more reliably than any lagging "
        "indicator based on OHLCV data. The book shows exactly where supply "
        "and demand sit, who is willing to pay what, and where the market "
        "will encounter resistance or support in the next few ticks.\n\n"
        "This agent computes bid/ask imbalance (the ratio of total bid size "
        "to total ask size across the top 10 levels), identifies liquidity "
        "gaps between price levels (zones with thin book depth where price "
        "can move quickly), detects resting walls (clusters of large limit "
        "orders that act as magnets or resistance), tracks spread width "
        "relative to its recent history, and estimates expected slippage "
        "for a position of the agent's target size. Queue dynamics measure "
        "whether the inside bid or ask is being eaten through or replenished. "
        "The agent never looks at 24h charts, funding rates, or any "
        "macro-level data — the microstructure is the complete picture at "
        "the decision horizon.\n\n"
        "## Entry Conditions\n\n"
        "**Required (all must be met):**\n"
        "1. Directional imbalance: bid/ask ratio > 1.5 (for longs) or\n"
        "   < 0.67 (for shorts) across the top 10 levels\n"
        "2. No resting wall within 0.5% of current price in the entry\n"
        "   direction (a large limit order cluster that would stop the move)\n"
        "3. Liquidity gap exists within 1% of current price in the entry\n"
        "   direction (thin book allowing clean price movement)\n"
        "4. Expected slippage for target size is < 0.1% of notional\n\n"
        "**Supporting (raise confidence, not required):**\n"
        "- Inside queue is being consumed, not replenished (aggressive flow\n"
        "  eating into the passive side)\n"
        "- Spread is tighter than the 20-period moving average (active market)\n"
        "- Recent small trades (1-5 contracts) are predominantly on the\n"
        "  aggressive side of the direction\n\n"
        "## Position Parameters\n\n"
        "- Direction: Determined by microstructure imbalance\n"
        "- Leverage: 4x (short hold times reduce gap risk)\n"
        "- Position size: 8% of account per trade (smaller because of\n"
        "  higher frequency and shorter horizons)\n"
        "- Stop loss: 1.0% from entry (tight — microstructure signal decays\n"
        "  quickly if wrong)\n"
        "- Take profit: 2.0% from entry (2:1 reward/risk for quick scalps)\n"
        "- Max hold time: 20 minutes; if TP not hit, exit on schedule\n\n"
        "## Known Weaknesses\n\n"
        "- Highly sensitive to book quality — during low liquidity periods\n"
        "  (e.g. weekends on altcoins), microstructure signals are noise\n"
        "- Transaction costs (spread + slippage) consume a meaningful\n"
        "  fraction of edge at this horizon — requires low-fee venue\n"
        "- News events overwhelm microstructure completely — flat before\n"
        "  known events\n"
        "- Most correlated to `amber_wolf` (trade flow) — microstructure\n"
        "  and flow are two sides of the same book\n\n"
        "## Assets in Focus\n\n"
        "Primary: BTC, ETH (deepest books, best microstructure signal)\n"
        "Secondary: SOL (good depth, consistent patterns)\n"
        "Avoid: Low-liquidity perps (PEPE, WIF, TRUMP) — book too thin\n",
    ),
    (
        "amber_wolf",
        "# amber_wolf — Thesis v1: Trade Flow\n\n"
        "## Edge Hypothesis\n\n"
        "Every market transaction carries information. Aggressive buyers "
        "(market buys lifting the ask) and aggressive sellers (market sells "
        "hitting the bid) reveal the direction of informed flow. By analysing "
        "every execution in real-time, the agent can detect when institutional "
        "or otherwise informed capital is moving directionally before that "
        "flow is fully reflected in the mid-price.\n\n"
        "Key metrics: aggressive buy volume vs aggressive sell volume over "
        "rolling windows (1m, 5m, 15m), VWAP relative to the mid-price "
        "(informed flow pays the spread — elevated VWAP above mid confirms "
        "buying pressure), buy pressure ratio (agg buys / total agg volume), "
        "average trade size (block trades vs retail — a surge in average "
        "size signals institutional participation), and cumulative delta "
        "(agg buys minus agg sells over a window). The signature of informed "
        "flow is overwhelming one-sided aggression at above-average trade "
        "size, sustained across multiple time windows.\n\n"
        "## Entry Conditions\n\n"
        "**Required (all must be met):**\n"
        "1. Buy pressure ratio > 0.65 (buy-heavy) or < 0.35 (sell-heavy)\n"
        "   across the 5-minute window\n"
        "2. Average trade size > 1.5x the 1-hour rolling average (confirms\n"
        "   institutional-sized participation, not retail noise)\n"
        "3. Cumulative delta is directionally consistent across all three\n"
        "   windows (1m, 5m, 15m) — no divergence pattern\n"
        "4. VWAP deviation from mid-price > 0.05% in the direction of flow\n"
        "   (aggressors are willing to pay up, confirming conviction)\n\n"
        "**Supporting (raise confidence, not required):**\n"
        "- Funding rate supports the flow direction (flow + funding = high\n"
        "  conviction)\n"
        "- Order book imbalance (from `gray_finch` style micro reading)\n"
        "  agrees with flow direction\n"
        "- Volume is accelerating into the move (1m > 5m > 15m on a\n"
        "  per-minute normalised basis)\n\n"
        "## Position Parameters\n\n"
        "- Direction: Direction of aggressive flow\n"
        "- Leverage: 3x\n"
        "- Position size: 10% of account per trade\n"
        "- Stop loss: 1.5% from entry\n"
        "- Take profit: 3.0% from entry (2:1 reward/risk)\n"
        "- Max hold time: 30 minutes — flow signals decay; if the move\n"
        "  hasn't materialised in 30m, the flow was likely absorption, not\n"
        "  accumulation\n\n"
        "## Known Weaknesses\n\n"
        "- In heavily algorithmic markets (BTC), trade flow can be\n"
        "  strategically spoofed or split across multiple venues\n"
        "- During low-volume periods, average trade size is unreliable\n"
        "- Flow analysis works best on mid-cap perps where institutional\n"
        "  flow is concentrated enough to measure\n"
        "- Correlated to `gray_finch` during high-volume regimes — both\n"
        "  read the same book from different angles\n\n"
        "## Assets in Focus\n\n"
        "Primary: SOL, SUI, ARB, OP (concentrated institutional flow)\n"
        "Secondary: BTC, ETH (deep flow but higher signal-to-noise ratio\n"
        "  required)\n"
        "Avoid: Meme coins (PEPE, WIF, DOGE) — retail-dominated flow\n",
    ),
    (
        "steel_crane",
        "# steel_crane — Thesis v1: Liquidation Hunter\n\n"
        "## Edge Hypothesis\n\n"
        "Crypto perpetual markets generate a unique and exploitable signal: "
        "forced liquidations. When leveraged positions are forcibly closed, "
        "the mechanical cascade creates temporary price dislocations that "
        "are both larger and more predictable than the efficient market "
        "hypothesis would predict. Liquidations create the opposite signal: "
        "long liquidations create downside pressure and then a vacuum that "
        "pulls price back; short liquidations create upside fuel.\n\n"
        "This agent monitors liquidation clusters (concentrated volumes at "
        "specific price levels), cascade history (chain liquidations that "
        "snowball as each liquidation pushes price further), leverage "
        "estimates from OI/price ratios (when estimated leverage is extreme, "
        "liquidations become more likely), funding rates (trapped longs "
        "paying high funding while underwater are prime cascade targets), "
        "and OI changes in the wake of liquidation events. The core question: "
        "is a squeeze likely? Has one already happened? If the cascade is "
        "in progress, the agent fades it — enters against the cascade "
        "direction expecting reversion as the book rebalances.\n\n"
        "## Entry Conditions\n\n"
        "**Required (all must be met):**\n"
        "1. Single-asset liquidation volume > $5M USD in the last 15 minutes\n"
        "   (meaningful cascade, not routine liquidations)\n"
        "2. Price has moved > 2% in the direction of the dominant liquidation\n"
        "   type (longs getting liquidated → price down; shorts getting\n"
        "   liquidated → price up)\n"
        "3. Estimated leverage (OI / notional value) > 15x for the asset\n"
        "   (extreme leverage = more fuel for the cascade)\n"
        "4. OI has dropped > 3% during the cascade (positions are being\n"
        "   removed from the book, reducing selling/buying pressure)\n\n"
        "**Supporting (raise confidence, not required):**\n"
        "- Funding rate was extreme before the cascade (funding + cascade\n"
        "  confluences — trapped positions are paying to stay in)\n"
        "- Multiple liquidation clusters visible on the book (cascades tend\n"
        "  to propagate through clustered liquidity)\n"
        "- Other assets in the same sector are not experiencing cascades\n"
        "  (idiosyncratic event, not systemic)\n"
        "- Regime tag is not crisis (systemic cascades are different)\n\n"
        "## Position Parameters\n\n"
        "- Direction: Counter-cascade. Long liquidations → Long.\n"
        "  Short liquidations → Short.\n"
        "- Leverage: 4x (higher leverage to compensate for rare-event\n"
        "  frequency — cascades happen infrequently but have high edge)\n"
        "- Position size: 8% per trade (conservative — cascade timing is\n"
        "  notoriously difficult)\n"
        "- Stop loss: 2.0% from entry\n"
        "- Take profit: 4.0% from entry (2:1 reward/risk)\n"
        "- Max hold time: 4 hours (cascades resolve quickly; if the\n"
        "  reversion hasn't happened in 4h, the thesis was wrong)\n\n"
        "## Known Weaknesses\n\n"
        "- Cascades can compound (cascading liquidations that trigger more\n"
        "  liquidations) — fading early gets run over\n"
        "- False cascades: a large single liquidation can look like a\n"
        "  cascade; need cluster detection to distinguish\n"
        "- Most effective on mid-cap perps (SOL, SUI, ARB) where liquidation\n"
        "  impact on price is highest\n"
        "- BTC cascades are deeper but fade more quickly — tighter edge\n\n"
        "## Assets in Focus\n\n"
        "Primary: SOL, SUI, ARB, OP, ETH (active liquidation markets)\n"
        "Secondary: BTC (deep but spreads edge thin)\n"
        "Avoid: Low-OI assets with <$10M daily liquidation volume\n",
    ),
    (
        "onyx_heron",
        "# onyx_heron — Thesis v1: Relative Value\n\n"
        "## Edge Hypothesis\n\n"
        "Within the crypto perpetuals universe, assets in the same sector "
        "or with structural relationships (SOL vs ETH, BTC vs ETH, AI-token "
        "basket vs Layer-1 basket) diverge and converge in statistically "
        "predictable patterns. These spreads are driven by temporary capital "
        "flows, narrative shifts, and leverage dynamics that mean-revert "
        "over hours to days. Trading the spread removes the need to predict "
        "absolute market direction — the edge comes from correctly identifying "
        "when one asset is statistically cheap or rich relative to another.\n\n"
        "The agent monitors a fixed set of pairs and baskets using z-score "
        "of the spread vs a rolling window, rolling correlation (assets must "
        "remain structurally related for the thesis to hold), and cointegration "
        "tests (pairs that drift apart must tend to revert, not diverge "
        "permanently). Entry is triggered when a spread is extreme (z-score "
        "> 2.0 or < -2.0) and cointegration is confirmed. The agent is always "
        "long the cheap leg and short the rich leg, reducing market beta to "
        "near zero when sized correctly.\n\n"
        "## Entry Conditions\n\n"
        "**Required (all must be met):**\n"
        "1. Spread z-score > 2.0 (asset A is expensive vs B) or < -2.0\n"
        "   (asset A is cheap vs B) based on the 7-day rolling window\n"
        "2. Rolling 20-period correlation between the two assets > 0.60\n"
        "   (the relationship still holds at the structural level)\n"
        "3. Cointegration test p-value < 0.05 (the spread is mean-reverting,\n"
        "   not a random walk divergence)\n"
        "4. The spread extreme is not driven by a known fundamental catalyst\n"
        "   on one leg (e.g. SOL network outage, ETH ETF news) — these are\n"
        "   regime changes, not mean-reversion setups\n\n"
        "**Supporting (raise confidence, not required):**\n"
        "- Funding rates on both legs are neutral (no artificial pressure)\n"
        "- The regime tag is range_low_vol or range_high_vol (mean-reversion\n"
        "  environments favour this thesis)\n"
        "- Other pairs in the same sector show normal spreads (idiosyncratic)\n"
        "- Spread has been extreme for 2+ hours (persistence confirms the\n"
        "  regime hasn't changed)\n\n"
        "## Position Parameters\n\n"
        "- Direction: Long the cheap leg, short the rich leg (always pair)\n"
        "- Leverage: 2x per leg, 4x total notional for the pair\n"
        "- Position size: 8% per leg (16% total notional per pair trade)\n"
        "- Stop loss: Spread widens by 2x the entry z-score (structural\n"
        "  break, not a routine retracement)\n"
        "- Take profit: Spread z-score returns to within ±0.5\n"
        "- Max hold time: 7 days — some spreads take days to converge;\n"
        "  re-evaluate daily\n\n"
        "## Known Weaknesses\n\n"
        "- Structural break risk: a previously cointegrated pair can\n"
        "  permanently diverge (e.g. ETH after the merge vs BTC)\n"
        "- Funding cost on the short leg can be significant over multi-day\n"
        "  holds — must factor into expected value\n"
        "- In trending regimes (trending_bull, trending_bear), the spread\n"
        "  can remain extreme for weeks\n"
        "- Requires two legs to be simultaneously liquid — limits universe\n\n"
        "## Pairs in Focus\n\n"
        "Primary: SOL/ETH, ETH/BTC, SOL/BTC, AI-basket/L1-basket\n"
        "Secondary: ARB/OP, SUI/APT, LINK/AAVE (sector pairs)\n"
        "Avoid: Meme coins against blue chips (no structural relationship)\n",
    ),
    (
        "jade_hawk",
        "# jade_hawk — Thesis v1: Regime Detection\n\n"
        "## Edge Hypothesis\n\n"
        "Market regime is the single most important conditioning variable for "
        "every trading strategy. A momentum strategy that thrives in trending "
        "markets destroys capital in ranging markets. A mean-reversion strategy "
        "that prints in range markets bleeds in trends. The most valuable "
        "agent on the desk is not the one that trades best — it is the one "
        "that correctly identifies what kind of market we are in right now.\n\n"
        "jade_hawk does not trade. It never recommends entry, exit, or "
        "position sizing directly. Its sole output is a regime classification "
        "tag that every other agent on the desk receives as part of their "
        "decision context. The classification uses inputs from across the "
        "market: BTC price action (trend direction and strength, measured by "
        "ADX and moving average slope), cross-asset volatility (ATR percentiles "
        "across the universe), funding rate distribution (are rates extreme\n"
        "across the board or neutral?), OI trends (aggregate OI rising or "
        "falling across the desk?), liquidation activity (elevated or normal?), "
        "and correlation structure (are assets moving together or rotating?).\n"
        "The output is one of nine regime tags, assigned deterministically "
        "with a confidence score, and the reasoning that led to the "
        "classification.\n\n"
        "## Regime Taxonomy\n\n"
        "1. **Trending** — Strong directional move with ADX > 25 and price\n"
        "   making higher highs / lower lows consistently. Sub-classified as\n"
        "   bullish or bearish.\n"
        "2. **Mean-reverting** — Range-bound price with no clear direction;\n"
        "   ATR is average or slightly above; price oscillates between\n"
        "   established support and resistance.\n"
        "3. **High volatility** — ATR > 90th percentile of 14-day range;\n"
        "   wide spreads, elevated liquidation activity; price gaps common.\n"
        "4. **Low volatility** — ATR < 20th percentile of 14-day range;\n"
        "   tight ranges, low volume, compressed spreads.\n"
        "5. **Risk-on** — BTC and alts rising together; funding rates positive\n"
        "   across the board; OI increasing; correlation matrix converging to\n"
        "   high values (everything moves together).\n"
        "6. **Risk-off** — BTC falling; alts falling more; funding across\n"
        "   assets negative (short premium); OI declining; correlation\n"
        "   spiking (fear-driven synchronous selling).\n"
        "7. **Funding frenzy** — Funding rates are extreme across 5+ assets\n"
        "   simultaneously; suggests market-wide positioning extreme.\n"
        "8. **Panic** — Liquidations cascading across multiple assets;\n"
        "   OI dropping sharply; spreads blowing out; VRP-like regime in\n"
        "   perps; this is a crisis classification.\n"
        "9. **Quiet accumulation** — Low volatility, neutral funding, stable\n"
        "   OI, correlation matrix normalising; price drifting sideways to\n"
        "   slightly up; this is the 'nobody cares' regime where smart money\n"
        "   positions.\n\n"
        "## Classification Method\n\n"
        "**Deterministic, not LLM-based.** The classifier is a decision tree "
        "with threshold-based rules derived from the input data. The output "
        "is a single regime tag and a confidence score (0.0-1.0) based on how "
        "many signals point to the same classification. When no single regime "
        "has high confidence (> 0.6), the tag is "mixed" and the confidence "
        "scores for all regimes are passed alongside so consuming agents can\n"
        "weight their decisions accordingly.\n\n"
        "**Required inputs for each classification cycle:**\n"
        "- BTC 4h OHLCV (last 30 candles)\n"
        "- ATR percentiles for BTC, ETH, SOL (14-day window)\n"
        "- Funding rates for all 15 universe assets\n"
        "- Aggregate OI change (across all assets, 24h)\n"
        "- Total liquidation volume (last 4 hours)\n"
        "- Average cross-asset correlation (20-period rolling)\n\n"
        "## Output Schema\n\n"
        "A regime report is written as a structured JSON object to the "
        "database and made available to all agents at decision time:\n\n"
        "```json\n"
        "{\n"
        "  \"regime\": \"trending_bull\",\n"
        "  \"confidence\": 0.82,\n"
        "  \"secondary\": {\"mean_reverting\": 0.12, \"high_vol\": 0.06},\n"
        "  \"reasoning\": \"BTC ADX at 32 with 4 consecutive 4h higher highs. \"\n"
        "    \"Funding neutral. OI rising 6% across the desk. \"\n"
        "    \"No elevated liquidation activity. Correlation at 0.75.\",\n"
        "  \"classifier_version\": 1\n"
        "}\n"
        "```\n\n"
        "## Interaction with Other Agents\n\n"
        "- Every other agent receives the regime tag and confidence in their\n"
        "  decision prompt\n"
        "- Agents are expected to condition their confidence on the regime:\n"
        "  a momentum agent should reduce size when regime is mean_reverting\n"
        "- The meta-agent (`crimson_fox`) uses jade_hawk's output as its\n"
        "  primary conditioning variable for confidence multipliers\n"
        "- When confidence is low (< 0.6), agents are told to use their own\n"
        "  best judgment and note the regime ambiguity\n\n"
        "## Known Weaknesses\n\n"
        "- Regime changes at inflection points are inherently lagging\n"
        "  (the classifier needs confirming candles)\n"
        "- During rapid regime transitions (e.g. panic from quiet),\n"
        "  the classifier can miss the transition until it is well underway\n"
        "- BTC-centric classification may miss altcoin-local regimes\n"
        "- Requires high-quality data across all 15 assets to be accurate\n"
        "- A deterministic classifier cannot adapt to novel regime types\n"
        "  without manual version updates\n",
    ),
    (
        "violet_lion",
        "# violet_lion — Thesis v1: Volatility Trader\n\n"
        "## Edge Hypothesis\n\n"
        "Volatility is a distinct asset class in crypto perpetuals that "
        "behaves independently of direction. Periods of artificially "
        "compressed volatility (ATR in the bottom 20th percentile, tight "
        "ranges, low volume) are followed by volatility expansion events "
        "that create opportunities regardless of which direction the price "
        "breaks. Conversely, periods of extreme volatility (ATR > 90th "
        "percentile) are statistically likely to contract, reducing the "
        "probability of large continuations.\n\n"
        "violet_lion does not take directional trades. It never predicts "
        "whether price will go up or down. Instead, it predicts the magnitude "
        "of future price movement and adjusts position sizing across the "
        "desk accordingly. When volatility is artificially compressed, the "
        "agent increases position size recommendations (the market is "
        "coiling and due for expansion). When volatility is extreme, it "
        "decreases position sizes (the market is unstable and directional "
        "edge is harder to find). violet_lion acts as a vol overlay on the "
        "desk, outputting a position-size multiplier that other agents "
        "reference.\n\n"
        "## Entry Conditions (Volatility State Classification)\n\n"
        "**Compressed regime (increase sizing):**\n"
        "1. ATR(14) across BTC, ETH, SOL is in the bottom 20th percentile\n"
        "   of its 60-day range\n"
        "2. Range compression: last 20 candles on 4h timeframe show a range\n"
        "   narrower than any 20-candle window in the last 60 days\n"
        "3. Average daily true range declining for 5+ consecutive days\n"
        "4. Volume declining or flat at compressed levels (confirms lack of\n"
        "   participation, not distribution)\n\n"
        "**Expanded regime (decrease sizing):**\n"
        "1. ATR(14) > 90th percentile of 60-day range\n"
        "2. Recent large candles (> 2x average range) without follow-through\n"
        "   (range expansion without trend — high noise)\n"
        "3. Spread widening across the book (market-maker risk premium\n"
        "   increasing)\n"
        "4. Elevated liquidation activity (cascading liquidations = vol\n"
        "  begets vol)\n\n"
        "## Output\n\n"
        "violet_lion writes a vol state report to the database containing:\n"
        "- Vol regime: compressed | normal | expanded | crisis\n"
        "- Position size multiplier: 1.5x (compressed), 1.0x (normal),\n"
        "  0.5x (expanded), 0.25x (crisis)\n"
        "- Confidence score (0.0-1.0)\n"
        "- ATR percentiles for each tracked asset\n"
        "- Expected vol expansion direction if compressed (no signal if\n"
        "  uncertainty is high)\n\n"
        "The multiplier is advisory — each agent decides whether and how\n"
        "to apply it. `crimson_fox` (meta agent) incorporates vol state\n"
        "into its confidence multiplier calculations.\n\n"
        "## Position Parameters\n\n"
        "- Direction: None (non-directional vol overlay)\n"
        "- Leverage: N/A\n"
        "- Position size: N/A — outputs a multiplier (0.25x to 1.5x)\n"
        "- Stop loss: N/A\n"
        "- Take profit: N/A\n\n"
        "## Known Weaknesses\n\n"
        "- Volatility compression can persist far longer than expected\n"
        "  (the 'coiled spring that never springs')\n"
        "- During crisis events, volatility explodes and the 0.25x\n"
        "  multiplier may still be too aggressive\n"
        "- ATR-based vol measures are inherently lagging — by the time\n"
        "  expansion is confirmed, the best entry may have passed\n"
        "- Overlap with jade_hawk's regime classifier: high volatility and\n"
        "  panic regimes often coincide\n\n"
        "## Assets in Focus\n\n"
        "All 15 universe assets — vol state is desk-wide, not per-asset\n",
    ),
    (
        "crimson_fox",
        "# crimson_fox — Thesis v1: Meta Agent\n\n"
        "## Edge Hypothesis\n\n"
        "The desk's collective historical performance contains latent patterns "
        "that no single strategy can see. Which agent performs best in which "
        "market regime? Which conditions produce the highest Sharpe for each "
        "strategy? How should confidence be allocated across the desk based "
        "on current market conditions? These questions define the meta-agent's "
        "domain — it does not study markets, it studies the other nine agents.\n\n"
        "crimson_fox analyses the full historical trade bank to learn which "
        "strategies produce edge in which regimes. It builds and maintains "
        "a performance matrix: for each known regime tag (from jade_hawk), "
        "it computes the win rate, Sharpe ratio, profit factor, and average "
        "return of every other agent. It then identifies which strategies "
        "are currently working, which are not, and which conditions signal "
        "a likely regime transition. Its output is a set of confidence "
        "multipliers for each other agent — a recommendation of how much "
        "to trust each strategy given the current market state.\n\n"
        "Over time, crimson_fox develops a meta-model: \"In trending_bull "
        "regimes, iron_moth has a 68% win rate with 1.9 Sharpe. When funding "
        "is extreme, silver_basin's mean-reversion produces 72% win rates "
        "but only in the first 4 hours. In low_vol regimes, gray_finch and\n"
        "amber_wolf both underperform — reduce allocation to 0.5x.\" This\n"
        "meta-knowledge may become the highest-Sharpe signal on the desk,\n"
        "as it compounds the edge of every other strategy through dynamic\n"
        "allocation.\n\n"
        "## Entry Conditions\n\n"
        "**crimson_fox does not enter trades directly.** It enters an "
        "analysis cycle:\n"
        "1. On every desk evaluation cycle (every 6h) or on demand via\n"
        "   meta-controller trigger\n"
        "2. When the trade bank has accumulated 10+ new closed trades since\n"
        "   the last analysis\n"
        "3. When the regime tag changes (jade_hawk posts a new classification)\n\n"
        "**Required data for each analysis cycle:**\n"
        "- All closed trades across all agents (last 7 days window minimum,\n"
        "  expanding to full history when meaningful)\n"
        "- Current regime tag + confidence from jade_hawk\n"
        "- Per-agent performance slices by regime (historical)\n"
        "- Per-agent performance slices by funding rate environment\n"
        "- Per-agent performance slices by volatility regime (from violet_lion)\n\n"
        "## Output\n\n"
        "A structured confidence report written to the database and broadcast\n"
        "to all agents at decision time:\n\n"
        "```json\n"
        "{\n"
        "  \"as_of\": \"2026-06-30T12:00:00Z\",\n"
        "  \"regime\": \"trending_bull\",\n"
        "  \"regime_confidence\": 0.82,\n"
        "  \"multipliers\": {\n"
        "    \"iron_moth\": 1.2,\n"
        "    \"silver_basin\": 0.6,\n"
        "    \"copper_vane\": 1.0,\n"
        "    \"gray_finch\": 1.1,\n"
        "    \"amber_wolf\": 1.0,\n"
        "    \"steel_crane\": 0.8,\n"
        "    \"onyx_heron\": 0.5,\n"
        "    \"jade_hawk\": 1.0,\n"
        "    \"violet_lion\": 1.0\n"
        "  },\n"
        "  \"reasoning\": \"In trending_bull regimes (N=85 trades over 14\n"
        "    days), iron_moth shows 1.9 Sharpe and 68% WR — momentum over-\n"
        "    performs. silver_basin has 0.8 Sharpe — funding extremes are\n"
        "    less reliable in strong trends. onyx_heron is at 0.5x as mean-\n"
        "    reversion pairs underperform in directional markets.\",\n"
        "  \"analysis_version\": 12\n"
        "}\n"
        "```\n\n"
        "## Output Integration\n\n"
        "- Every other agent receives its multiplier in the decision prompt:\n"
        "  \"crimson_fox confidence multiplier for your strategy: 1.2x\"\n"
        "- Agents are encouraged (not required) to scale their conviction by\n"
        "  this multiplier when sizing\n"
        "- The risk gate does not enforce multipliers — they are advisory\n"
        "- The meta-controller can use the confidence report to prioritise\n"
        "  which agents to evaluate first or allocate more compute to\n\n"
        "## Known Weaknesses\n\n"
        "- Needs a critical mass of trades before its outputs are meaningful\n"
        "  (100+ across the desk minimum)\n"
        "- In a regime shift, historical performance is a liability — the\n"
        "  matrix takes time to re-calibrate\n"
        "- Over-optimisation risk: if the trade bank is small, multipliers\n"
        "  can overfit to noise\n"
        "- Most exposed to shared failure modes: if all agents are wrong\n"
        "  in the same way, the meta-agent compounds the error\n"
        "- The meta-agent is the most complex agent and the hardest to\n"
        "  validate — wrong multipliers can damage the whole desk\n",
    ),
]


def main():
    print("=" * 60)
    print("FORGE — Fresh Start")
    print("=" * 60)
    print()
    print("This will DELETE ALL EXISTING DATA and seed 10 new agents.")
    print()

    if len(sys.argv) > 1 and sys.argv[1] == "--yes":
        confirmed = True
    else:
        resp = input("Are you sure? (y/N): ").strip().lower()
        confirmed = resp in ("y", "yes")

    if not confirmed:
        print("Cancelled.")
        return

    # Wipe existing DB (including WAL/SHM sidecar files from journal_mode=WAL)
    if DB_PATH.exists():
        DB_PATH.unlink()
        print(f"Deleted existing database: {DB_PATH}")
    else:
        print("No existing database found.")

    for suffix in ("-wal", "-shm"):
        sidecar = DB_PATH.with_name(DB_PATH.name + suffix)
        if sidecar.exists():
            sidecar.unlink()
            print(f"Deleted stale sidecar file: {sidecar}")

    # Initialize fresh schema
    conn = get_connection(str(DB_PATH))
    init_schema(conn)

    # Seed agents
    for name, thesis in SEED_AGENTS:
        agent = spawn_agent(
            conn,
            name,
            thesis,
            status="rookie",
            starting_balance=STARTING_BALANCE,
        )
        print(
            f"  Created agent: {name} (status={agent['status']}, balance=${STARTING_BALANCE:,.0f})"
        )

    conn.close()

    # Verify
    conn = get_connection(str(DB_PATH))
    count = conn.execute("SELECT COUNT(*) FROM agents").fetchone()[0]
    bal_count = conn.execute(
        "SELECT COUNT(*) FROM accounts WHERE mode='paper'"
    ).fetchone()[0]
    conn.close()

    print()
    print(f"Done. {count} agents seeded, {bal_count} account snapshots created.")
    print()
    print("Ready. Run: python forge.py")


if __name__ == "__main__":
    main()
