"""scripts/fresh_start.py -- Reset the desk and seed all 10 initial agents.

WARNING: This deletes ALL existing data in the database.
Run only when you want a clean start.
"""
import sys
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from store.db import get_connection, init_schema
from meta.spawner import spawn_agent

DB_PATH = PROJECT_ROOT / "data" / "forge.db"
STARTING_BALANCE = 50_000.0

SEED_AGENTS = [
    (
        "iron_moth",
        "# iron_moth -- Thesis v1: Cross-sectional Momentum\n\n"
        "## Edge Hypothesis\n\n"
        "Cross-sectional momentum across the perpetuals universe produces "
        "persistent, uncorrelated alpha that is independent of absolute market "
        "direction. By ranking all assets in the universe on multiple return "
        "horizons (30m, 2h, 12h, 24h) and entering the strongest relative "
        "performers, the agent captures the tendency of winning assets to "
        "continue outperforming losers within the same asset class -- the "
        "textbook momentum premium adapted for crypto perps.\n\n"
        "Momentum alone is noisy. The edge is sharpened by requiring "
        "momentum acceleration (the most recent horizon > longer horizons) "
        "and volatility-adjusted returns (Sharpe ratio of the momentum signal "
        "over the lookback). Sector-relative momentum excludes trades that "
        "are just beta -- if all assets are rising, the agent prioritises "
        "assets rising the most within their sector peer group. Funding rate "
        "and order book data are explicitly ignored to keep the signal pure.\n\n"
        "## Entry Conditions\n\n"
        "**Required (all must be met):**\n"
        "1. Asset ranks in top 3 of universe by composite momentum score\n"
        "   (weighted average of normalized 30m, 2h, 12h, 24h returns)\n"
        "2. Momentum acceleration confirmed: most recent horizon return\n"
        "   exceeds the average of all longer horizons\n"
        "3. Volatility-adjusted return > 0.5 (return / ATR over lookback)\n"
        "4. Sector-relative rank is top 2 within the asset's sector peer group\n\n"
        "**Supporting (raise confidence, not required):**\n"
        "- Asset is not the highest-correlation member of its sector to BTC\n"
        "- Volume is above the 14-day median (confirms participation)\n"
        "- No conflicting regime tag (e.g. avoid fresh crisis regime)\n\n"
        "## Position Parameters\n\n"
        "- Direction: Long only (cross-sectional momentum on perps favors\n"
        "  the long side due to funding cost on shorts)\n"
        "- Leverage: 3x\n"
        "- Position size: 12% of account per trade\n"
        "- Stop loss: 2.5% below entry price\n"
        "- Take profit: 5.0% above entry price (2:1 reward/risk)\n"
        "- Max hold time: 12 hours; if TP not hit, re-evaluate at next wake\n\n"
        "## Known Weaknesses\n\n"
        "- Underperforms during sharp trend reversals when momentum flips\n"
        "- High correlation to other long-biased strategies on the desk\n"
        "- Mean-reversion regimes (range_high_vol) generate whipsaws\n"
        "- In low-vol regimes the ranking becomes noise-dominated\n\n"
        "## Assets in Focus\n\n"
        "Primary: SOL, ETH, SUI, AVAX, LINK (higher momentum dispersion)\n"
        "Secondary: BTC (lower momentum variance but anchor position)\n"
        "Avoid: Stablecoin pairs and assets with <$50M daily volume\n",
    ),
    (
        "silver_basin",
        "# silver_basin -- Thesis v1: Funding Dislocation\n\n"
        "## Edge Hypothesis\n\n"
        "Funding rates are the purest expression of leverage demand in the "
        "crypto perpetuals market. When traders are willing to pay extreme "
        "premiums (positive funding) or receive extreme discounts (negative "
        "funding), they are expressing a conviction that is statistically "
        "likely to be wrong at the extreme. Funding dislocations are "
        "self-correcting: the cost of holding a trade mechanically reduces "
        "the edge of the crowded side until it unwinds.\n\n"
        "This agent studies nothing but funding. It computes the current "
        "funding rate z-score vs a rolling 14-day history, the funding trend "
        "(direction of the last 3 periods), predicted funding from OI changes "
        "(when OI surges, funding tends to follow), and funding acceleration "
        "(the rate of change of funding itself). Entry is triggered when "
        "funding is statistically irrational -- extreme z-scores combined with "
        "accelerating trend -- and held until funding normalises. Price action "
        "is deliberately excluded to avoid confirmation bias.\n\n"
        "## Entry Conditions\n\n"
        "**Required (all must be met):\n"
        "1. Funding rate z-score > 2.0 (positive extreme) or < -2.0 (negative\n"
        "   extreme) against 14-day rolling window\n"
        "2. Funding acceleration confirms the extreme -- the last period's\n"
        "   change is in the same direction as the dislocation\n"
        "3. OI change supports the thesis: for positive funding extreme,\n"
        "   OI should be flat or falling (late-stage crowding); for negative\n"
        "   funding extreme, OI should be stable or rising (building shorts)\n"
        "4. No major scheduled event for the asset in the next 4 hours\n"
        "   (earnings, major unlocks, regulatory decisions)\n\n"
        "**Supporting (raise confidence, not required):**\n"
        "- Funding has been extreme for 2+ consecutive periods (persistence)\n"
        "- Predicted funding from OI model agrees with current extreme\n"
        "- Other assets in same sector show normal funding (idiosyncratic)\n\n"
        "## Position Parameters\n\n"
        "- Direction: For positive extreme: Short (fade the long premium).\n"
        "  For negative extreme: Long (fade the short premium)\n"
        "- Leverage: 4x (higher leverage because mean reversion is time-bound\n"
        "  by funding settlement)\n"
        "- Position size: 10% of account per trade\n"
        "- Stop loss: 2.0% from entry (tight -- if funding doesn't revert soon,\n"
        "  the thesis is wrong)\n"
        "- Take profit: Exit when funding z-score returns to within ±1.0\n"
        "  (the signal resolves, not a price target)\n"
        "- Max hold time: Until next funding settlement (max 8 hours)\n\n"
        "## Known Weaknesses\n\n"
        "- In persistent trends, funding can stay extreme for days -- this\n"
        "  agent bleeds to the trend\n"
        "- Most correlated to `jade_hawk` (VWAP mean reversion) -- both fade\n"
        "  extremes, jade_hawk from price and this agent from funding\n"
        "- Low volatility regimes with stable funding produce no signals\n"
        "- Gap risk: funding normalises via a sharp move that hits the SL\n"
        "  first, then continues in the thesis direction\n\n"
        "## Assets in Focus\n\n"
        "Primary: SOL, ETH, ARB, OP, SUI (high funding variance)\n"
        "Secondary: BTC (lower funding variance but deeper liquidity)\n"
        "Avoid: PEPE, DOGE, WIF (funding too noisy, low predictive value)\n",
    ),
    (
        "copper_vane",
        "# copper_vane -- Thesis v1: Open Interest Intelligence\n\n"
        "## Edge Hypothesis\n\n"
        "Open interest reveals conviction behind price moves better than "
        "price alone. The OI×Price regime matrix classifies market states "
        "into four categories, each with a clear directional implication:\n\n"
        "- Rising price + rising OI = genuine new participation. Capital is\n"
        "  entering the asset, longs and shorts are both adding. This is\n"
        "  a healthy trend -- go with it.\n"
        "- Rising price + falling OI = short squeeze or distribution. Price\n"
        "  is rising but total exposure is shrinking -- shorts are being\n"
        "  forced out or smart money is distributing. Fade the move.\n"
        "- Falling price + rising OI = aggressive new shorts. Capital is\n"
        "  entering on the short side, indicating informed selling. Join it.\n"
        "- Falling price + falling OI = longs giving up. Capitulation without\n"
        "  new short conviction -- wait for reversal.\n\n"
        "OI data from Hyperliquid updates every few seconds and reflects "
        "real on-chain positioning. This signal is difficult to spoof and "
        "leads price, especially at turning points. The agent ignores raw "
        "price action as a primary signal and classifies every 4-hour window "
        "into one of the four OI×Price quadrants, entering only when the "
        "classification is unambiguous.\n\n"
        "## Entry Conditions\n\n"
        "**Required (all must be met):**\n"
        "1. Clear OI×Price regime classification confirmed for the current\n"
        "   4-hour window with no ambiguity (direction consistency in both\n"
        "   axes over the full window)\n"
        "2. OI change magnitude > 3% in the classification direction\n"
        "   (confirms the signal is meaningful, not noise)\n"
        "3. Price change magnitude > 1.5% (confirms the move has market\n"
        "   impact)\n"
        "4. No conflicting OI regime in the prior 4-hour window\n"
        "   (reversal signals require two consecutive windows to confirm)\n\n"
        "**Supporting (raise confidence, not required):**\n"
        "- Volume confirms: volume direction matches OI direction\n"
        "- Funding rate is neutral or supports the OI thesis\n"
        "- The OI change is broad across the sector (not just one asset)\n\n"
        "## Position Parameters\n\n"
        "- Direction: Determined by OI×Price quadrant classification.\n"
        "   Rising+Rising = Long. Rising+Falling = Short. Falling+Rising =\n"
        "   Short. Falling+Falling = Wait (no entry).\n"
        "- Leverage: 3x\n"
        "- Position size: 12% of account per trade\n"
        "- Stop loss: 2.0% from entry\n"
        "- Take profit: 4.0% from entry (2:1 reward/risk)\n"
        "- Max hold time: 8 hours\n\n"
        "## Known Weaknesses\n\n"
        "- In low-volume regimes, OI changes are small and classification\n"
        "  becomes unreliable\n"
        "- OI data can lag during high-volatility events on Hyperliquid\n"
        "- After large liquidation cascades, OI drops mechanically -- this\n"
        "  creates false 'falling+falling' signals\n"
        "- Most effective on mid-cap perps (SOL, ARB, SUI) where OI\n"
        "  changes are driven by conviction, not passive hedging\n\n"
        "## Assets in Focus\n\n"
        "Primary: SOL, ETH, SUI, ARB, OP (good OI depth)\n"
        "Secondary: BTC, BNB (deep OI but lower predictive variance)\n"
        "Avoid: Assets with <$10M OI (noise-dominated)\n",
    ),
    (
        "gray_finch",
        "# gray_finch -- Thesis v1: Order Book Microstructure\n\n"
        "## Edge Hypothesis\n\n"
        "Over short time horizons (5-20 minutes), order book microstructure "
        "predicts imminent price direction more reliably than any lagging "
        "indicator based on OHLCV data. The book shows exactly where supply "
        "and demand sit, who is willing to pay what, and where the market "
        "will encounter resistance or support in the next few ticks.\n\n"
        "This agent computes bid/ask imbalance (the ratio of total bid size "
        "to total ask size across the top 10 levels), identifies liquidity "
        "gaps between price levels (zones with thin book depth where price "
        "can move quickly), detects resting walls (clusters of large limit "
        "orders that act as magnets or resistance), tracks spread width "
        "relative to its recent history, and estimates expected slippage "
        "for a position of the agent's target size. Queue dynamics measure "
        "whether the inside bid or ask is being eaten through or replenished. "
        "The agent never looks at 24h charts, funding rates, or any "
        "macro-level data -- the microstructure is the complete picture at "
        "the decision horizon.\n\n"
        "## Entry Conditions\n\n"
        "**Required (all must be met):**\n"
        "1. Directional imbalance: bid/ask ratio > 1.5 (for longs) or\n"
        "   < 0.67 (for shorts) across the top 10 levels\n"
        "2. No resting wall within 0.5% of current price in the entry\n"
        "   direction (a large limit order cluster that would stop the move)\n"
        "3. Liquidity gap exists within 1% of current price in the entry\n"
        "   direction (thin book allowing clean price movement)\n"
        "4. Expected slippage for target size is < 0.1% of notional\n\n"
        "**Supporting (raise confidence, not required):**\n"
        "- Inside queue is being consumed, not replenished (aggressive flow\n"
        "  eating into the passive side)\n"
        "- Spread is tighter than the 20-period moving average (active market)\n"
        "- Recent small trades (1-5 contracts) are predominantly on the\n"
        "  aggressive side of the direction\n\n"
        "## Position Parameters\n\n"
        "- Direction: Determined by microstructure imbalance\n"
        "- Leverage: 4x (short hold times reduce gap risk)\n"
        "- Position size: 8% of account per trade (smaller because of\n"
        "  higher frequency and shorter horizons)\n"
        "- Stop loss: 1.0% from entry (tight -- microstructure signal decays\n"
        "  quickly if wrong)\n"
        "- Take profit: 2.0% from entry (2:1 reward/risk for quick scalps)\n"
        "- Max hold time: 20 minutes; if TP not hit, exit on schedule\n\n"
        "## Known Weaknesses\n\n"
        "- Highly sensitive to book quality -- during low liquidity periods\n"
        "  (e.g. weekends on altcoins), microstructure signals are noise\n"
        "- Transaction costs (spread + slippage) consume a meaningful\n"
        "  fraction of edge at this horizon -- requires low-fee venue\n"
        "- News events overwhelm microstructure completely -- flat before\n"
        "  known events\n"
        "- Most correlated to `amber_wolf` (trade flow) -- microstructure\n"
        "  and flow are two sides of the same book\n\n"
        "## Assets in Focus\n\n"
        "Primary: BTC, ETH (deepest books, best microstructure signal)\n"
        "Secondary: SOL (good depth, consistent patterns)\n"
        "Avoid: Low-liquidity perps (PEPE, WIF, TRUMP) -- book too thin\n",
    ),
    (
        "amber_wolf",
        "# amber_wolf -- Thesis v1: Trade Flow\n\n"
        "## Edge Hypothesis\n\n"
        "Every market transaction carries information. Aggressive buyers "
        "(market buys lifting the ask) and aggressive sellers (market sells "
        "hitting the bid) reveal the direction of informed flow. By analysing "
        "every execution in real-time, the agent can detect when institutional "
        "or otherwise informed capital is moving directionally before that "
        "flow is fully reflected in the mid-price.\n\n"
        "Key metrics: aggressive buy volume vs aggressive sell volume over "
        "rolling windows (1m, 5m, 15m), VWAP relative to the mid-price "
        "(informed flow pays the spread -- elevated VWAP above mid confirms "
        "buying pressure), buy pressure ratio (agg buys / total agg volume), "
        "average trade size (block trades vs retail -- a surge in average "
        "size signals institutional participation), and cumulative delta "
        "(agg buys minus agg sells over a window). The signature of informed "
        "flow is overwhelming one-sided aggression at above-average trade "
        "size, sustained across multiple time windows.\n\n"
        "## Entry Conditions\n\n"
        "**Required (all must be met):**\n"
        "1. Buy pressure ratio > 0.65 (buy-heavy) or < 0.35 (sell-heavy)\n"
        "   across the 5-minute window\n"
        "2. Average trade size > 1.5x the 1-hour rolling average (confirms\n"
        "   institutional-sized participation, not retail noise)\n"
        "3. Cumulative delta is directionally consistent across all three\n"
        "   windows (1m, 5m, 15m) -- no divergence pattern\n"
        "4. VWAP deviation from mid-price > 0.05% in the direction of flow\n"
        "   (aggressors are willing to pay up, confirming conviction)\n\n"
        "**Supporting (raise confidence, not required):**\n"
        "- Funding rate supports the flow direction (flow + funding = high\n"
        "  conviction)\n"
        "- Order book imbalance (from `gray_finch` style micro reading)\n"
        "  agrees with flow direction\n"
        "- Volume is accelerating into the move (1m > 5m > 15m on a\n"
        "  per-minute normalised basis)\n\n"
        "## Position Parameters\n\n"
        "- Direction: Direction of aggressive flow\n"
        "- Leverage: 3x\n"
        "- Position size: 10% of account per trade\n"
        "- Stop loss: 1.5% from entry\n"
        "- Take profit: 3.0% from entry (2:1 reward/risk)\n"
        "- Max hold time: 30 minutes -- flow signals decay; if the move\n"
        "  hasn't materialised in 30m, the flow was likely absorption, not\n"
        "  accumulation\n\n"
        "## Known Weaknesses\n\n"
        "- In heavily algorithmic markets (BTC), trade flow can be\n"
        "  strategically spoofed or split across multiple venues\n"
        "- During low-volume periods, average trade size is unreliable\n"
        "- Flow analysis works best on mid-cap perps where institutional\n"
        "  flow is concentrated enough to measure\n"
        "- Correlated to `gray_finch` during high-volume regimes -- both\n"
        "  read the same book from different angles\n\n"
        "## Assets in Focus\n\n"
        "Primary: SOL, SUI, ARB, OP (concentrated institutional flow)\n"
        "Secondary: BTC, ETH (deep flow but higher signal-to-noise ratio\n"
        "  required)\n"
        "Avoid: Meme coins (PEPE, WIF, DOGE) -- retail-dominated flow\n",
    ),
    (
        "steel_crane",
        "# steel_crane -- Thesis v1: Liquidation Hunter\n\n"
        "## Edge Hypothesis\n\n"
        "Crypto perpetual markets generate a unique and exploitable signal: "
        "forced liquidations. When leveraged positions are forcibly closed, "
        "the mechanical cascade creates temporary price dislocations that "
        "are both larger and more predictable than the efficient market "
        "hypothesis would predict. Liquidations create the opposite signal: "
        "long liquidations create downside pressure and then a vacuum that "
        "pulls price back; short liquidations create upside fuel.\n\n"
        "This agent monitors liquidation clusters (concentrated volumes at "
        "specific price levels), cascade history (chain liquidations that "
        "snowball as each liquidation pushes price further), leverage "
        "estimates from OI/price ratios (when estimated leverage is extreme, "
        "liquidations become more likely), funding rates (trapped longs "
        "paying high funding while underwater are prime cascade targets), "
        "and OI changes in the wake of liquidation events. The core question: "
        "is a squeeze likely? Has one already happened? If the cascade is "
        "in progress, the agent fades it -- enters against the cascade "
        "direction expecting reversion as the book rebalances.\n\n"
        "## Entry Conditions\n\n"
        "**Required (all must be met):**\n"
        "1. Single-asset liquidation volume > $5M USD in the last 15 minutes\n"
        "   (meaningful cascade, not routine liquidations)\n"
        "2. Price has moved > 2% in the direction of the dominant liquidation\n"
        "   type (longs getting liquidated → price down; shorts getting\n"
        "   liquidated → price up)\n"
        "3. Estimated leverage (OI / notional value) > 15x for the asset\n"
        "   (extreme leverage = more fuel for the cascade)\n"
        "4. OI has dropped > 3% during the cascade (positions are being\n"
        "   removed from the book, reducing selling/buying pressure)\n\n"
        "**Supporting (raise confidence, not required):**\n"
        "- Funding rate was extreme before the cascade (funding + cascade\n"
        "  confluences -- trapped positions are paying to stay in)\n"
        "- Multiple liquidation clusters visible on the book (cascades tend\n"
        "  to propagate through clustered liquidity)\n"
        "- Other assets in the same sector are not experiencing cascades\n"
        "  (idiosyncratic event, not systemic)\n"
        "- Regime tag is not crisis (systemic cascades are different)\n\n"
        "## Position Parameters\n\n"
        "- Direction: Counter-cascade. Long liquidations → Long.\n"
        "  Short liquidations → Short.\n"
        "- Leverage: 4x (higher leverage to compensate for rare-event\n"
        "  frequency -- cascades happen infrequently but have high edge)\n"
        "- Position size: 8% per trade (conservative -- cascade timing is\n"
        "  notoriously difficult)\n"
        "- Stop loss: 2.0% from entry\n"
        "- Take profit: 4.0% from entry (2:1 reward/risk)\n"
        "- Max hold time: 4 hours (cascades resolve quickly; if the\n"
        "  reversion hasn't happened in 4h, the thesis was wrong)\n\n"
        "## Known Weaknesses\n\n"
        "- Cascades can compound (cascading liquidations that trigger more\n"
        "  liquidations) -- fading early gets run over\n"
        "- False cascades: a large single liquidation can look like a\n"
        "  cascade; need cluster detection to distinguish\n"
        "- Most effective on mid-cap perps (SOL, SUI, ARB) where liquidation\n"
        "  impact on price is highest\n"
        "- BTC cascades are deeper but fade more quickly -- tighter edge\n\n"
        "## Assets in Focus\n\n"
        "Primary: SOL, SUI, ARB, OP, ETH (active liquidation markets)\n"
        "Secondary: BTC (deep but spreads edge thin)\n"
        "Avoid: Low-OI assets with <$10M daily liquidation volume\n",
    ),
    (
        "onyx_heron",
        "# onyx_heron -- Thesis v1: Relative Value\n\n"
        "## Edge Hypothesis\n\n"
        "Within the crypto perpetuals universe, assets in the same sector "
        "or with structural relationships (SOL vs ETH, BTC vs ETH, AI-token "
        "basket vs Layer-1 basket) diverge and converge in statistically "
        "predictable patterns. These spreads are driven by temporary capital "
        "flows, narrative shifts, and leverage dynamics that mean-revert "
        "over hours to days. Trading the spread removes the need to predict "
        "absolute market direction -- the edge comes from correctly identifying "
        "when one asset is statistically cheap or rich relative to another.\n\n"
        "The agent monitors a fixed set of pairs and baskets using z-score "
        "of the spread vs a rolling window, rolling correlation (assets must "
        "remain structurally related for the thesis to hold), and cointegration "
        "tests (pairs that drift apart must tend to revert, not diverge "
        "permanently). Entry is triggered when a spread is extreme (z-score "
        "> 2.0 or < -2.0) and cointegration is confirmed. The agent is always "
        "long the cheap leg and short the rich leg, reducing market beta to "
        "near zero when sized correctly.\n\n"
        "## Entry Conditions\n\n"
        "**Required (all must be met):**\n"
        "1. Spread z-score > 2.0 (asset A is expensive vs B) or < -2.0\n"
        "   (asset A is cheap vs B) based on the 7-day rolling window\n"
        "2. Rolling 20-period correlation between the two assets > 0.60\n"
        "   (the relationship still holds at the structural level)\n"
        "3. Cointegration test p-value < 0.05 (the spread is mean-reverting,\n"
        "   not a random walk divergence)\n"
        "4. The spread extreme is not driven by a known fundamental catalyst\n"
        "   on one leg (e.g. SOL network outage, ETH ETF news) -- these are\n"
        "   regime changes, not mean-reversion setups\n\n"
        "**Supporting (raise confidence, not required):**\n"
        "- Funding rates on both legs are neutral (no artificial pressure)\n"
        "- The regime tag is range_low_vol or range_high_vol (mean-reversion\n"
        "  environments favour this thesis)\n"
        "- Other pairs in the same sector show normal spreads (idiosyncratic)\n"
        "- Spread has been extreme for 2+ hours (persistence confirms the\n"
        "  regime hasn't changed)\n\n"
        "## Position Parameters\n\n"
        "- Direction: Long the cheap leg, short the rich leg (always pair)\n"
        "- Leverage: 2x per leg, 4x total notional for the pair\n"
        "- Position size: 8% per leg (16% total notional per pair trade)\n"
        "- Stop loss: Spread widens by 2x the entry z-score (structural\n"
        "  break, not a routine retracement)\n"
        "- Take profit: Spread z-score returns to within ±0.5\n"
        "- Max hold time: 7 days -- some spreads take days to converge;\n"
        "  re-evaluate daily\n\n"
        "## Known Weaknesses\n\n"
        "- Structural break risk: a previously cointegrated pair can\n"
        "  permanently diverge (e.g. ETH after the merge vs BTC)\n"
        "- Funding cost on the short leg can be significant over multi-day\n"
        "  holds -- must factor into expected value\n"
        "- In trending regimes (trending_bull, trending_bear), the spread\n"
        "  can remain extreme for weeks\n"
        "- Requires two legs to be simultaneously liquid -- limits universe\n\n"
        "## Pairs in Focus\n\n"
        "Primary: SOL/ETH, ETH/BTC, SOL/BTC, AI-basket/L1-basket\n"
        "Secondary: ARB/OP, SUI/APT, LINK/AAVE (sector pairs)\n"
        "Avoid: Meme coins against blue chips (no structural relationship)\n",
    ),
    (
        "jade_hawk",
        "# jade_hawk -- Thesis v1: VWAP Mean Reversion\n\n"
        "\n"
        "## Edge Hypothesis\n"
        "\n"
        "Price consistently overshoots and reverts to VWAP across multiple timeframes, especially at statistical extremes. VWAP acts as a gravitational centre for price: institutions execute large orders algorithmically around VWAP, market-makers hedge around it, and the settlement mechanics of perps create natural reversion pressure. When price deviates significantly from VWAP -- more than two ATRs away on a 15-minute chart -- the probability of reversion within the next 1-4 hours increases well above random.\n"
        "\n"
        "This agent fades price extremes relative to VWAP. It does not predict direction -- it predicts that price is statistically stretched and will revert toward the mean. Every momentum agent on the desk buys strength; jade_hawk sells it and buys weakness. This negative correlation to the desk's trend strategies provides natural diversification.\n"
        "\n"
        "The signal is strongest when multiple timeframe VWAPs (15m, 1h, 4h) all show deviation in the same direction, confirming that the move is extended on multiple execution horizons. Volume confirmation distinguishes a climax (reversion likely) from a genuine breakout (momentum likely).\n"
        "\n"
        "## Entry Conditions\n"
        "\n"
        "**Required (all must be met):**\n"
        "\n"
        "**For short entries (price overextended above VWAP):**\n"
        "1. Current price > VWAP(1h) + 2.0 * ATR(14) on the 15-minute chart\n"
        "2. VWAP(4h) is also below current price (multi-timeframe confirmation)\n"
        "3. Volume on the move is > 1.5x the 14-period average volume on the 15m chart (climax volume, not quiet drift)\n"
        "4. The move has been sustained for at least 3 consecutive 15m candles (not a single wick)\n"
        "\n"
        "**For long entries (price compressed below VWAP):**\n"
        "1. Current price < VWAP(1h) - 2.0 * ATR(14) on the 15-minute chart\n"
        "2. VWAP(4h) is also above current price (multi-timeframe confirmation)\n"
        "3. Volume on the move is > 1.5x the 14-period average volume\n"
        "4. The move has been sustained for at least 3 consecutive 15m candles\n"
        "\n"
        "**Supporting (raise confidence, not required):**\n"
        "- RSI(14) on 1h chart > 70 (short) or < 30 (long) -- classic overbought/oversold\n"
        "- Funding rate supports the fade direction (extreme positive funding + price above VWAP = strong short signal)\n"
        "- The regime is range_low_vol or range_high_vol (mean-reversion environments)\n"
        "- No major scheduled event for the asset in the next 4 hours\n"
        "- The move is not driven by a liquidation cascade (would favour steel_crane for the fade, not this strategy)\n"
        "\n"
        "## Position Parameters\n"
        "\n"
        "- Direction: Short when price is overextended above VWAP. Long when price is compressed below VWAP.\n"
        "- Leverage: 3x\n"
        "- Position size: 10% of account per trade\n"
        "- Stop loss: 1.5% from entry (tight -- if price doesn't revert soon, the thesis is wrong)\n"
        "- Take profit: VWAP(1h) level (the mean itself is the target)\n"
        "- Max hold time: 4 hours; if price hasn't reverted to VWAP in 4 hours, the market structure has shifted\n"
        "\n"
        "## Known Weaknesses\n"
        "\n"
        "- In strong trending regimes (trending_bull, trending_bear), price can stay extended past VWAP for days -- this agent bleeds to the trend\n"
        "- Most correlated to `silver_basin` (funding mean-reversion) -- both fade extremes, but from different signal dimensions\n"
        "- Gap moves through VWAP without reversion (flash crashes, news events) produce instant SL hits\n"
        "- In high-volatility regimes (crisis), VWAP bands are too wide to be meaningful -- the agent should reduce size or skip\n"
        "- Bollinger Band-like strategies are well-known; edge compression is real when many participants trade the same mean-reversion setup\n"
        "\n"
        "## Assets in Focus\n"
        "\n"
        "Primary: SOL, ETH, AVAX, LINK (clean VWAP behaviour, consistent mean reversion)\n"
        "Secondary: BTC (tight VWAP bands, lower edge per trade)\n"
        "Avoid: PEPE, DOGE, WIF, TRUMP (noisy price action, VWAP less reliable as gravity)\n",
    ),
    (
        "violet_lion",
        "# violet_lion -- Thesis v1: Volatility Regime Trader\n\n"
        "\n"
        "## Edge Hypothesis\n"
        "\n"
        "Volatility compresses and expands in predictable cycles. Periods of artificially compressed volatility (ATR in the bottom 25th percentile, tight Bollinger Band width, low volume) are followed by directional expansion events. Periods of extreme volatility (ATR > 80th percentile, wide spreads, elevated liquidations) are statistically likely to contract -- the emotional overreaction fades. The key insight: these volatility regime transitions create directional trading opportunities that are distinct from trend, mean-reversion, or flow signals.\n"
        "\n"
        "When vol is compressed, the market is coiling. The direction of the coming breakout is unknown ex-ante, but the edge comes from entering with the breakout once it begins, using microstructure clues (book imbalance, aggressive flow) to pick the side. When vol is already expanded, the edge comes from fading the emotional extreme -- the market has overreacted and a mean-reverting snap-back is probable.\n"
        "\n"
        "This strategy differs from pure mean reversion (jade_hawk) because it does not trade price deviation from VWAP. It trades the vol regime transition itself. In compression it is a breakout follower; in expansion it is a volatility fade. The regime state determines the mode.\n"
        "\n"
        "## Entry Conditions\n"
        "\n"
        "**Compressed regime (coil -- anticipate breakout):**\n"
        "\n"
        "**Required:**\n"
        "1. ATR(14) on the target asset is in the bottom 25th percentile of its 30-day range\n"
        "2. Bollinger Band width (20, 2) is at or below the 20th percentile of its 30-day range (bands are squeezing)\n"
        "3. Volume is below the 14-day median (confirms lack of participation, not distribution)\n"
        "4. Price breaks beyond the tight range: a 15m candle closes above the highest high or below the lowest low of the preceding 10 candles\n"
        "5. Microstructure confirmation: bid/ask imbalance (from book data) or aggressive flow direction (from trade flow) supports the breakout direction\n"
        "\n"
        "**Supporting (raise confidence, not required):**\n"
        "- Volume on the breakout candle > 1.5x average 15m volume\n"
        "- Funding is neutral (no artificial positioning pressure)\n"
        "- The breakout direction aligns with the dominant regime (trending regime + upside vol breakout = strong confluence)\n"
        "- Narrowing of Bollinger Bands has been sustained for 5+ candles\n"
        "\n"
        "**Expanded regime (vol fade -- fade the extreme):**\n"
        "\n"
        "**Required:**\n"
        "1. ATR(14) > 80th percentile of its 30-day range\n"
        "2. A recent 15m candle has exceeded 2x the average candle range (extreme candle)\n"
        "3. The move lacks follow-through: the next 1-2 candles retrace at least 30% of the extreme candle\n"
        "4. Funding rate is extreme in the direction of the move (crowded positioning -- fade is safer)\n"
        "\n"
        "**Supporting (raise confidence, not required):**\n"
        "- Liquidation cascade has already occurred (steel_crane would have entered; this agent joins the fade after the cascade peak)\n"
        "- The extreme candle closed with a long wick (rejection at the extreme)\n"
        "- OI dropped during the move (positions being liquidated, reducing fuel for continuation)\n"
        "\n"
        "## Position Parameters\n"
        "\n"
        "**Compressed regime (breakout):**\n"
        "- Direction: Direction of the breakout (long above range high, short below range low)\n"
        "- Leverage: 3x\n"
        "- Position size: 8% of account per trade (smaller -- breakouts have higher variance)\n"
        "- Stop loss: 1.5% from entry (tight -- false breakouts are common)\n"
        "- Take profit: 3.0% from entry (ride the breakout)\n"
        "- Max hold time: 4 hours\n"
        "\n"
        "**Expanded regime (fade):**\n"
        "- Direction: Counter to the extreme move. Long after a sell climax, short after a buying climax.\n"
        "- Leverage: 3x\n"
        "- Position size: 8% of account\n"
        "- Stop loss: 1.5% from entry\n"
        "- Take profit: 2.0% from entry (fade is a quick scalp, not a hold)\n"
        "- Max hold time: 2 hours (vol fades resolve fast or they fail)\n"
        "\n"
        "## Known Weaknesses\n"
        "\n"
        "- False breakouts in compression are the strategy's primary risk -- tight SLs get hit routinely, and the real move starts after the agent is stopped out\n"
        "- Fading expanded vol during a genuine cascade continuation (flash crash extending) can compound losses -- requires steel_crane's liquidation data to avoid overlapping\n"
        "- ATR is inherently lagging: by the time compression is identified, the market may have been coiling for days already, and the breakout may come much later\n"
        "- Requires microstructure data for direction selection -- dependence on the same signals as gray_finch and amber_wolf, creating correlation in compressed regimes\n"
        "- Most correlated to `steel_crane` during expanded vol (both fade extremes) and to `amber_wolf` during compressed regimes (both follow flow)\n"
        "- In range_high_vol regimes with no clear expansion/compression cycle, the agent may flip between modes too frequently\n"
        "\n"
        "## Assets in Focus\n"
        "\n"
        "Primary: SOL, ETH, SUI (clean vol cycles, reliable compression/expansion patterns)\n"
        "Secondary: BTC (lower vol variance, but tighter compression signals)\n"
        "Avoid: Low-liquidity perps (PEPE, WIF, TRUMP) -- vol is permanently elevated, making compression signals unreliable\n",
    ),
    (
        "crimson_fox",
        "# crimson_fox -- Thesis v1: Session Pattern Arbitrage\n\n"
        "\n"
        "## Edge Hypothesis\n"
        "\n"
        "Crypto perpetuals trade 24/7 across global sessions, but participation, order flow, and directional bias follow predictable daily and weekly patterns. These time-based patterns exist because different sets of participants dominate at different hours: APAC retail and systematic flows in the Asian session, European institutions during London hours, US leveraged players at the NY open. Each transition between these participant cohorts creates exploitable directional drift.\n"
        "\n"
        "The edge is small per trade but highly reliable and available every single day. This is a compounding strategy, not a home-run strategy. The agent does not predict market direction from price action or volume -- it knows what time it is and what statistically tends to happen at that time.\n"
        "\n"
        "Trading is restricted to specific session windows where historical edge has been established. Outside these windows the agent waits.\n"
        "\n"
        "## Session Definitions (all times UTC)\n"
        "\n"
        "### US Open (12:00--13:30 UTC, Mon--Fri)\n"
        "The highest-volume 90 minutes of the day. BTC and alts frequently gap or break in the first 30 minutes of US cash equities opening. The edge: trade the direction of the first 15-minute candle with a tight stop. If the first 15m candle is green, go long; if red, go short. The US open directional bias has persistence for 60--90 minutes on ~60% of trading days.\n"
        "\n"
        "### US Afternoon Reversal (16:00--18:00 UTC, Mon--Fri)\n"
        "The 'puppet show' period where algo desks and institutional flow push into the close. Statistically significant reversal from the US morning trend. If price moved up during the US session (12:00--16:00), expect a mean-reverting pullback. If price moved down, expect a bounce. This is the highest-Sharpe session window.\n"
        "\n"
        "### Asian Session Drift (00:00--02:00 UTC, Mon--Fri)\n"
        "Lower liquidity, wider spreads, but consistent directional drift from systematic APAC flows. The edge: trade the direction of the first 30-minute candle of the Asian session. The drift tends to persist for 1--3 hours and is most reliable when it follows a quiet US session (low volatility carries through).\n"
        "\n"
        "### Weekly Patterns\n"
        "- **Monday open (00:00 UTC)**: Weekend gap fills are common in the first 4 hours. If BTC gapped up over the weekend, expect a fill-down; if gapped down, expect a fill-up.\n"
        "- **Friday afternoon (14:00--18:00 UTC)**: Position squaring before the weekend. Longs are closed, shorts are covered. Creates mean-reverting moves.\n"
        "- **Funding settlement windows (00:00, 08:00, 16:00 UTC)**: Positioning changes 30--60 minutes before settlement as traders adjust leveraged positions. Mild directional bias in the hour leading into settlement.\n"
        "\n"
        "## Entry Conditions\n"
        "\n"
        "**Required (all must be met):**\n"
        "1. Current time falls within a defined session window (US Open, US Reversal, Asian Drift, or weekly pattern)\n"
        "2. The session has a direction signal based on its rule (first candle direction, session trend reversal, gap fill)\n"
        "3. Volume confirms participation is at expected session levels (not a holiday/thin session)\n"
        "4. No major scheduled event for BTC or any target asset in the next 2 hours (macro news, CPI, FOMC, major unlocks)\n"
        "\n"
        "**Supporting (raise confidence, not required):**\n"
        "- The session signal aligns with the market regime (e.g., trend regime + US Open direction = strong confluence)\n"
        "- The prior session showed low volatility (quiet carry-through increases pattern reliability)\n"
        "- Multiple session patterns align simultaneously (e.g., it's Monday US Open AND a weekend gap exists)\n"
        "- Funding is neutral or supports the session direction\n"
        "\n"
        "## Position Parameters\n"
        "\n"
        "- Direction: Per session rule. US Open: direction of first 15m candle. US Reversal: counter to session trend. Asian Drift: direction of first 30m candle. Weekly: gap fill direction.\n"
        "- Leverage: 2x (lower -- time-based edges are small but consistent)\n"
        "- Position size: 8% of account per trade\n"
        "- Stop loss: 1.0% from entry (tight -- time-based edge is invalidated quickly if wrong)\n"
        "- Take profit: Session exit condition (TP at 1.5% or session end, whichever comes first)\n"
        "- Max hold time: Until the session window closes (maximum 4 hours for Asian drift, 90 minutes for US Open)\n"
        "\n"
        "## Entry Rules Summary\n"
        "\n"
        "| Session | When (UTC) | Entry Rule | Max Hold |\n"
        "|---------|-----------|------------|----------|\n"
        "| US Open | Mon--Fri 12:00 | Direction of first 15m candle | 90 min |\n"
        "| US Reversal | Mon--Fri 16:00 | Counter to US session trend (12:00--16:00) | 2h |\n"
        "| Asian Drift | Mon--Fri 00:00 | Direction of first 30m candle | 3h |\n"
        "| Monday Gap | Mon 00:00--04:00 | Counter to weekend gap direction | 4h |\n"
        "| Friday Squaring | Fri 14:00--18:00 | Counter to week's last 4h direction | 4h |\n"
        "| Pre-settlement | 07:00--08:00, 15:00--16:00, 23:00--00:00 | Direction of improving funding rate | 1h |\n"
        "\n"
        "## Known Weaknesses\n"
        "\n"
        "- Small edge per trade requires many repetitions -- statistical significance takes weeks of trading\n"
        "- Major macro news (FOMC, CPI, NFP) completely overrides session patterns -- must flat through known events\n"
        "- DST transitions and holiday weeks shift session boundaries -- reduced reliability during transitions\n"
        "- Weekend sessions (Saturday--Sunday) do not have reliable patterns -- agent skips them entirely\n"
        "- Most vulnerable to structural market changes that break historical patterns (e.g., ETF approval changing US open behaviour permanently)\n"
        "- Lowest Sharpe agent on the desk individually -- value is as a uncorrelated compounding machine alongside the other strategies\n"
        "- Session boundaries are approximate; exact timing shifts with market structure -- requires periodic re-calibration\n"
        "\n"
        "## Assets in Focus\n"
        "\n"
        "Primary: BTC, ETH (most consistent session behaviour across all time windows)\n"
        "Secondary: SOL (growing session consistency, particularly in US hours)\n"
        "Avoid: Small-cap perps -- session patterns are unreliable when the asset itself drives the flow rather than macro session dynamics\n",
    ),
]


def main():
    print("=" * 60)
    print("FORGE -- Fresh Start")
    print("=" * 60)
    print()
    print("This will DELETE ALL EXISTING DATA and seed 10 new agents.")
    print()

    if len(sys.argv) > 1 and sys.argv[1] == "--yes":
        confirmed = True
    else:
        resp = input("Are you sure? (y/N): ").strip().lower()
        confirmed = resp in ("y", "yes")

    if not confirmed:
        print("Cancelled.")
        return

    # Wipe existing DB (including WAL/SHM sidecar files from journal_mode=WAL)
    if DB_PATH.exists():
        DB_PATH.unlink()
        print(f"Deleted existing database: {DB_PATH}")
    else:
        print("No existing database found.")

    for suffix in ("-wal", "-shm"):
        sidecar = DB_PATH.with_name(DB_PATH.name + suffix)
        if sidecar.exists():
            sidecar.unlink()
            print(f"Deleted stale sidecar file: {sidecar}")

    # Initialize fresh schema
    conn = get_connection(str(DB_PATH))
    init_schema(conn)

    # Seed agents
    for name, thesis in SEED_AGENTS:
        agent = spawn_agent(
            conn,
            name,
            thesis,
            status="rookie",
            starting_balance=STARTING_BALANCE,
        )
        print(
            f"  Created agent: {name} (status={agent['status']}, balance=${STARTING_BALANCE:,.0f})"
        )

    conn.close()

    # Verify
    conn = get_connection(str(DB_PATH))
    count = conn.execute("SELECT COUNT(*) FROM agents").fetchone()[0]
    bal_count = conn.execute(
        "SELECT COUNT(*) FROM accounts WHERE mode='paper'"
    ).fetchone()[0]
    conn.close()

    print()
    print(f"Done. {count} agents seeded, {bal_count} account snapshots created.")
    print()
    print("Ready. Run: python forge.py")


if __name__ == "__main__":
    main()
